### ISSUE TITLE
You also have simple php?

### ISSUE THREAD

**Issue by DemOnJR** [luigifab38/paypalrefund#1]
You have an PayPal refund ony for php? not mvc or plugin for some cms, simple php thanks.

**Comment by luigifab38** [comment]
No, but you can get the content of the method **refund** of the source file [app/code/community/Luigifab/Paypalrefund/Model/Rewrite/Standard.php](https://github.com/luigifab38/paypalrefund/blob/master/app/code/community/Luigifab/Paypalrefund/Model/Rewrite/Standard.php).

**Comment by DemOnJR** [comment]
Thanks.
